"use client";

import { useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Question={id:string;question:string;options:string[];correctIndex:number;correctAnswer?:string|null;points?:number;type:"multiple_choice"|"multiple_select"|"complete"|"numerical"|"true_false"};
type Attempt={score:number;total:number};
type Answer=string|number|number[];

export default function QuizPlayer({quizId,title,questions,attempts:initialAttempts,maxAttempts,kidsMode}:{quizId:string;title:string;questions:Question[];attempts:Attempt[];maxAttempts:number|null;kidsMode:boolean}){
 const supabase=createClient();const startedAt=useRef(Date.now());const[answers,setAnswers]=useState<Record<string,Answer>>({});const[attempts,setAttempts]=useState(initialAttempts);const[retrying,setRetrying]=useState(initialAttempts.length===0);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState<string|null>(null);const canRetry=maxAttempts===null||attempts.length<maxAttempts;const best=attempts.reduce<Attempt|null>((b,a)=>!b||a.score/a.total>b.score/b.total?a:b,null);
 async function submit(){setSubmitting(true);setError(null);let score=0;const total=questions.reduce((s,q)=>s+(q.points??1),0);for(const q of questions){const answer=answers[q.id];const pts=q.points??1;let ok=false;if(q.type==="complete"){const expected=(q.correctAnswer??q.options[0]??"").trim().toLocaleLowerCase();ok=String(answer??"").trim().toLocaleLowerCase()===expected;}else if(q.type==="numerical"){ok=Number(answer)===Number(q.correctAnswer??q.options[0]);}else if(q.type==="multiple_select"){let expected:number[]=[];try{expected=JSON.parse(q.correctAnswer??"[]")}catch{};const actual:number[]=Array.isArray(answer)?answer:[];ok=expected.length===actual.length&&expected.every(x=>actual.includes(x));}else ok=answer===q.correctIndex;if(ok)score+=pts;}
  const{data:{user}}=await supabase.auth.getUser();if(!user){setError("انتهت الجلسة. سجّل الدخول مرة أخرى.");setSubmitting(false);return;}const{error:insertError}=await supabase.from("quiz_attempts").insert({quiz_id:quizId,user_id:user.id,score,total,answers,duration_seconds:Math.max(1,Math.round((Date.now()-startedAt.current)/1000))});if(insertError){setError("تعذر حفظ النتيجة. حاول مرة أخرى.");setSubmitting(false);return;}setAttempts(a=>[...a,{score,total}]);setAnswers({});setRetrying(false);setSubmitting(false);}
 if(!retrying)return <div className="border-t border-line pt-4 mt-2"><p className={kidsMode?"text-base font-bold text-[#7a3fa0] mb-2":"text-sm font-medium text-ink mb-1"}>{title}</p><span className="inline-block text-xs bg-green-light text-green-text px-2.5 py-1 rounded-full">أعلى نتيجة: {best?.score} من {best?.total}</span><p className="text-xs text-ink-faint mt-2">عدد المحاولات: {attempts.length}{maxAttempts!==null?` من ${maxAttempts}`:""}</p>{canRetry?<button onClick={()=>{startedAt.current=Date.now();setRetrying(true)}} className="mt-3 bg-green text-white text-sm font-medium py-2 px-5 rounded-md">إعادة المحاولة</button>:<p className="text-xs text-ink-faint mt-3">خلصت المحاولات المتاحة.</p>}</div>;
 const allAnswered=questions.every(q=>{const a=answers[q.id];if(a===undefined)return false;if(Array.isArray(a))return a.length>0;return String(a).trim()!=="";});
 return <div className="border-t border-line pt-4 mt-2 space-y-4"><p className={kidsMode?"text-base font-bold text-[#7a3fa0]":"text-sm font-medium text-ink"}>{kidsMode?"🎯 ":""}{title}</p>{questions.map((q,qi)=><div key={q.id} className={kidsMode?"bg-[#fff8ec] border-2 border-[#ffd166] rounded-2xl p-4":"bg-paper rounded-lg p-4"}><div className="flex justify-between gap-3 mb-3"><p className="text-sm text-ink">{qi+1}. {q.question}</p><span className="text-[11px] text-ink-faint whitespace-nowrap">{q.points??1} نقطة</span></div>{q.type==="complete"?<input value={String(answers[q.id]??"")} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} placeholder="اكتب الإجابة هنا" className="w-full px-3 py-2 border border-line rounded-md bg-surface text-sm"/>:q.type==="numerical"?<input type="number" value={String(answers[q.id]??"")} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} placeholder="اكتب الرقم" className="w-full px-3 py-2 border border-line rounded-md bg-surface text-sm"/>:<div className="space-y-1.5">{q.options.map((opt,oi)=>{const current=answers[q.id];const selected:number[]=Array.isArray(current)?current:[];const checked=q.type==="multiple_select"?selected.includes(oi):current===oi;return <label key={oi} className="flex items-center gap-2 text-sm text-ink-soft"><input type={q.type==="multiple_select"?"checkbox":"radio"} name={q.id} checked={checked} onChange={e=>{if(q.type==="multiple_select"){const value=answers[q.id];const cur:number[]=Array.isArray(value)?value:[];setAnswers(a=>({...a,[q.id]:e.target.checked?[...cur,oi]:cur.filter(x=>x!==oi)}));}else setAnswers(a=>({...a,[q.id]:oi}));}}/>{opt}</label>})}</div>}</div>)}{error&&<p className="text-sm text-red-600">{error}</p>}<button onClick={submit} disabled={!allAnswered||submitting} className="bg-green text-white text-sm font-medium py-2 px-5 rounded-md disabled:opacity-50">{submitting?"جاري التصحيح…":"تسليم الإجابات"}</button></div>;
}
