"use client";
import { useState } from "react";
import BackButton from "@/components/back-button";

type Credential={name:string;email:string;password:string};
export default function BulkStudentsPage(){
 const[loading,setLoading]=useState(false),[message,setMessage]=useState<string|null>(null),[credentials,setCredentials]=useState<Credential[]>([]);
 async function create(){setLoading(true);setMessage(null);setCredentials([]);try{const r=await fetch("/api/admin/bulk-create-students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({count:30,grade:"Grade 4",groupName:"Grade 4 - Class A",namePrefix:"طالب الصف الرابع",emailDomain:"ather.local"})});const d=await r.json();if(!r.ok){setMessage(d.error??"تعذر إنشاء الحسابات");return}setCredentials(d.credentials??[]);setMessage(`تم إنشاء ${d.count} من ${d.requested} حسابًا وربطهم تلقائيًا بـ Grade 4 - Class A.`);if(d.errors?.length)setMessage(`تم إنشاء ${d.count} حسابًا، مع ${d.errors.length} ملاحظات.`)}catch{setMessage("تعذر الاتصال بالخادم.")}finally{setLoading(false)}}
 function download(){const text=credentials.map((c,i)=>`${i+1}.\t${c.name}\t${c.email}\t${c.password}`).join("\n");const blob=new Blob([`#\tالاسم\tالبريد\tكلمة المرور\n${text}`],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="ather-grade4-class-a-credentials.txt";a.click();URL.revokeObjectURL(url)}
 return <div className="min-h-screen bg-paper"><div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-10"><div className="mb-4"><BackButton/></div><h1 className="font-display text-2xl font-medium text-ink">إنشاء حسابات الطلاب دفعة واحدة 🚀</h1><p className="text-sm text-ink-soft mt-1 mb-7">30 حساب طالب للصف الرابع، مع ربط تلقائي بفصل Grade 4 - Class A.</p><div className="bg-surface border border-line rounded-xl p-5"><button onClick={()=>void create()} disabled={loading} className="bg-green text-white rounded-md px-5 py-2.5 text-sm font-medium disabled:opacity-60">{loading?"جاري إنشاء 30 حسابًا…":"إنشاء 30 حسابًا الآن"}</button>{message&&<p className="text-sm text-ink-soft mt-3">{message}</p>}{credentials.length>0&&<div className="mt-5"><div className="flex flex-wrap items-center gap-2 mb-3"><button onClick={download} className="border border-line rounded-md px-3 py-1.5 text-xs">⬇️ حفظ بيانات الدخول</button><span className="text-xs text-ink-faint">كلمات المرور لا تُخزّن كنص واضح؛ احفظ هذا الملف بعد الإنشاء.</span></div><div className="overflow-auto border border-line rounded-lg"><table className="w-full text-xs"><thead><tr className="bg-paper text-right"><th className="p-2">#</th><th className="p-2">الاسم</th><th className="p-2">البريد</th><th className="p-2">كلمة المرور</th></tr></thead><tbody>{credentials.map((c,i)=><tr key={c.email} className="border-t border-line"><td className="p-2">{i+1}</td><td className="p-2">{c.name}</td><td dir="ltr" className="p-2 text-left">{c.email}</td><td dir="ltr" className="p-2 font-mono text-left">{c.password}</td></tr>)}</tbody></table></div></div>}</div></div></div>;
}
